uploads = []
generated = []

[[outputs]]
id = "9NS4HnXlh8P5FIi_9ywxQ"
uri = "file://exports/JEAN_X_JAY_script_completo.txt"
type = "text"
title = "Script JEAN X JAY completo"

[[outputs]]
id = "-F_Rs-DwETppQ-fH-76re"
uri = "file://exports/BENJA_script_completo.txt"
type = "text"
title = "Script BENJA completo"
